name: Codespell

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

# Start the job on all pushes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set the Job
jobs:
  build:
    name: Codespell
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps
    steps:
      # Check out the code base
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run linter against code base
      # https://github.com/codespell-project/codespell
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_file: .codespellignore
          skip: "*.csv,*.dkvp,*.txt,*.js,*.html,*.map,./tags,./test/cases,./docs/src/shapes-of-data.md.in,./docs/src/shapes-of-data.md"
